name: clash
url: https://api.sebs.club/ssr/e7be579d-3c90-427c-ba5b-1f942e317faa
nodes: [{type: ssr, cipher: aes-256-cfb, password: 123456m, name: digitalocean 新加坡,
    server: sgp.sijia.ooo, port: 1024, protocol: origin, obfs: plain, group: ONESubscribe},
  {type: ssr, cipher: aes-256-cfb, password: 123456m, name: google 洛杉矶, server: g.sijia.ooo,
    port: 1024, protocol: origin, obfs: plain, group: ONESubscribe}, {type: ssr, cipher: aes-256-cfb,
    password: 123456m, name: google 台湾, server: gt.sijia.ooo, port: 1024, protocol: origin,
    obfs: plain, group: ONESubscribe}, {type: ssr, cipher: aes-256-cfb, password: 123456m,
    name: google 香港, server: gh.sijia.ooo, port: 1024, protocol: origin, obfs: plain,
    group: ONESubscribe}, {type: ssr, cipher: aes-256-cfb, password: 123456m, name: azure
      香港, server: az.sijia.ooo, port: 1024, protocol: origin, obfs: plain, group: ONESubscribe}]
lastUpdate: 2019-12-27T23:15:17.820637+08:00
